### ISSUE TITLE
No such file or directory: './data/Movie/train_tok.json'

### ISSUE THREAD

**Issue by Howene** [turboLJY/CapsGNN-Review-Generation#1]
Thanks for your great ideas, codes, paper, and so on. I can not wait to run the codes to observe its amazing output. After I ran the commands "CUDA_LAUNCH_BLOCKING=1
python main.py --train Movie --save_dir ./data/Movie
python main.py --load Movie --save_dir ./data/Movie --load_file <saved_aspect_model_file_for_movie>", 

it had reported some bugs as follows:
"load data...
Start loading training data ...
Saved data not found, start preparing training data ...
vocabs <load.Vocabulary object at 0x7f46680db6d8>
Reading ./data/Movie/train_tok.json
Traceback (most recent call last):
  File "../load.py", line 113, in loadPrepareData
    train_pairs = torch.load(os.path.join(save_dir, 'train_pairs.tar'))
  File "/lib/python3.6/site-packages/torch/serialization.py", line 579, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/lib/python3.6/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/lib/python3.6/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: './data/Movie/train_pairs.tar'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 80, in <module>
    run(args)
  File "main.py", line 67, in run
    capsule_num, args.save_dir)
  File "/CapsGNN-Review-Generation/aspect/train.py", line 115, in trainIters
    vocabs, train_pairs, valid_pairs, test_pairs = loadPrepareData(corpus, save_dir)  # load data
  File "../load.py", line 121, in loadPrepareData
    train_pairs, valid_pairs, test_pairs = prepareData(vocabs, save_dir)
  File "../load.py", line 99, in prepareData
    train_pairs = tokenize(os.path.join(save_dir, 'train_tok.json'), vocabs)
  File "../load.py", line 70, in tokenize
    with open(path, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: './data/Movie/train_tok.json'
run.sh: 4: Syntax error: newline unexpected"

Then I guessed it may be caused by the missing of the "train_tok.json" file, so I change the codes in line 70 of  the "load.py" file "with open(path, 'r') as f:" as "with open(path, 'w+') as f:", it reported other bugs as follows:
"
load data...
Start loading training data ...
load data finish...
Training pairs not found, generating ...
Traceback (most recent call last):
  File "/CapsGNN-Review-Generation/aspect/train.py", line 124, in trainIters
    training_batches = torch.load(os.path.join(data_path, '{}_{}.tar'.format('training_batches', batch_size)))
  File "/lib/python3.6/site-packages/torch/serialization.py", line 579, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/lib/python3.6/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/lib/python3.6/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: './data/Movie/batches/training_batches_1024.tar'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 80, in <module>
    run(args)
  File "main.py", line 67, in run
    capsule_num, args.save_dir)
  File "/CapsGNN-Review-Generation/aspect/train.py", line 127, in trainIters
    training_batches = batchify(train_pairs, batch_size, vocabs)
  File "/CapsGNN-Review-Generation/aspect/train.py", line 103, in batchify
    add_sam = random.sample(pairs, add_num)
  File "/lib/python3.6/random.py", line 320, in sample
    raise ValueError("Sample larger than population or is negative")
ValueError: Sample larger than population or is negative
run.sh: 4: Syntax error: newline unexpected
"

So what caused these bugs? Could you help me get it to work well? Thanks!

**Comment by Howene** [comment]
Hi, I tried several ways to solve this problem, but I haven't fixed it yet. Are the dataset files are completed?  Could you check them again? Thanks!
